added sentry icon
ceph/pulpito-ng pull request #18
Opened 2023-06-10 10:25 UTC by Med16-11

Resolved issue #6
![Screenshot from 2023-06-10 15-26-44](https://github.com/ceph/pulpito-ng/assets/78318301/720809cb-de02-49b9-89e2-d6ff6dc067ae)

2023-06-12 13:21 UTC, kamoltat requested changes
Please sign your commit using `commit -s`

2023-06-12 15:29 UTC, Med16-11 commented
Done.

2023-06-13 16:11 UTC, kamoltat commented
Can you squash the 3 commits into 1, using git rebase -i HEAD~3. Thanks

2023-06-14 15:58 UTC, zmc commented
The icon should go in `./public/` like the favicon

2023-06-14 16:53 UTC, Med16-11 commented
adding icon in public folder is throwing the following error-
You attempted to import ../../../public/sentry.svg which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.

2023-06-14 19:38 UTC, kamoltat commented
For the record, I still think the asset should live in `src/components/JobList/assets/`
stack overflow gave a good explanation to why: https://stackoverflow.com/questions/44643041/do-i-store-image-assets-in-public-or-src-in-reactjs

2023-06-14 19:44 UTC, zmc commented
Oh you're absolutely right @Med16-11 and @kamoltat! Apologies. I was moving too fast and forgot we were _importing_ the svg.

2023-06-14 19:45 UTC, zmc approved these changes

2023-06-14 19:48 UTC, kamoltat commented
no worries!

2023-06-15 12:31 UTC, Med16-11 commented
@kamoltat made the required changes

2023-06-16 16:27 UTC, kamoltat commented
@Med16-11 your commit contains changes from devansh's commit: https://github.com/ceph/pulpito-ng/commit/c4c71d3b21e4e90548be3a416034c2422ba8e151

before pushing, always utilize `git log` and `git diff` to review your changes.

2023-06-16 16:48 UTC, kamoltat commented
@Med16-11 
so for me the cleanest way to this is probably `git reset --hard HEAD~1` and just make your changes again. Be sure to note down what you have changed tho so you don't forget.

2023-06-16 17:31 UTC, Med16-11 commented
@kamoltat  have a look now.

2023-06-16 18:05 UTC, kamoltat commented
@Med16-11 Your commit message shouldn't be `Made final change`, it should describe the changes you have made. I suggest at the bare minimum put something like `added sentry icon`. Commit messages are important, it saves time for reviewers and future developers.

2023-06-16 19:33 UTC, Med16-11 commented
sure, done.

2023-06-21 00:27 UTC, zmc approved these changes

2023-06-21 14:58 UTC, kamoltat approved these changes

2023-06-21 15:16 UTC, kamoltat commented
hmm seems like github thinks the commit is not signed, I tried closing and opening the PR to refresh that part of check, still didn't work ... @Med16-11 you used `commit -s` to sign your commit right?

2023-06-21 23:20 UTC, merged