Init Dockerfile & containerized pulpito-ng
ceph/pulpito-ng pull request #22
Opened 2023-06-24 19:48 UTC by kamoltat

Motivation:

We need a way to connect `pulpito-ng`
with `teuthology-api` + all other teuthology services. Currently, we make use of docker containers to create a development environment for `teuthology-api` and other teuthology services.

Solution:

Created a Dockerfile and added a section in the README file describing the process of connecting `pulpito-ng` with otheer teuthology services such that we will be able to containerize `pulpito-ng` and develop it along side other services.

2023-06-28 16:23 UTC, zmc commented on Dockerfile
> +COPY package.json /app
probably package-lock as well

2023-07-17 17:48 UTC, kamoltat commented
@zmc should we try to merge this? I think we agreed on keep the docker-compose stuff for now so this will help the interns to develop easier.

2023-07-17 20:26 UTC, zmc commented
@kamoltat yeah, I still want to try restoring the docs subdir before merging; I just haven't had a chance to yet. I'll mark this as a draft until then.

2023-07-18 13:34 UTC, kamoltat commented
@zmc can we merge this first since it will be easier for the interns to run pulpito-ng in a container with other services, so that can start working on integrating pulpitp-ng with teuthology-api.

2023-07-18 15:50 UTC, zmc commented
@kamoltat 🤦 when I saw your comment I somehow thought you were talking about the teuthology PR - I have no idea why. Sorry!

This can be merged now.

2023-07-18 15:53 UTC, zmc requested changes

2023-07-18 15:53 UTC, zmc commented on README.md
> +In [teuthology's docker-compose](https://github.com/ceph/teuthology/blob/main/docs/docker-compose/docker-compose.yml) replace `pulpito` service with the following line:
```suggestion
In [teuthology's docker-compose](https://github.com/ceph/teuthology/blob/main/docs/docker-compose/docker-compose.yml) replace `pulpito` service with the following:
```
It's not just one line

2023-07-19 13:44 UTC, kamoltat commented on README.md
> +In [teuthology's docker-compose](https://github.com/ceph/teuthology/blob/main/docs/docker-compose/docker-compose.yml) replace `pulpito` service with the following line:
@zmc done!

2023-07-21 00:01 UTC, zmc approved these changes

2023-07-21 00:03 UTC, zmc commented
Looks like we have a merge conflict @kamoltat - should be an easy one to fix, though

2023-07-21 17:57 UTC, zmc commented
I set up automated container builds for this repo, so once we get this PR merged we will have containers available here: https://quay.io/repository/ceph-infra/pulpito-ng

2023-07-25 16:09 UTC, kamoltat commented
@zmc should be good

2023-07-25 16:32 UTC, zmc approved these changes

2023-07-25 16:32 UTC, merged

2023-07-25 17:11 UTC, zmc commented
Quay seems to be broken at the moment; the build started 40min ago and hasn't completed. I started a second one and it appears hung as well.

2023-07-25 22:08 UTC, zmc commented
Built and pushed manually to: https://quay.ceph.io/repository/ceph/pulpito-ng
We'll need a real solution, of course, but this is _something_ :)