pages/Run/index.tsx: Add kill run button
ceph/pulpito-ng pull request #51
Opened 2023-08-13 16:51 UTC by Devansh3712

This PR solves issue #2 which adds a kill run button that will kill all jobs in the current run. It currently uses a mock API endpoint for success alert, needs to be connected to the teuthology-api

![Screenshot (102)](https://github.com/ceph/pulpito-ng/assets/58616444/c02a7b71-d429-40aa-8353-a22d2676fcac)

2023-12-01 21:13 UTC, VallariAg commented
Changes made:
- Rebased the branch to main
- Added a commit which 
   - moves the code from Run Page to two new components `Alert` and `KillButton`
   - uses react-query's `useMutation` to send a POST request at t-api's /kill endpoint

TODO:
- show kill button **_only_** when signed-in-user == scheduler-user
- add kill button on Job Page (to kill a job)
- add a pop-up dialog box which says something like "are you sure you want to kill this run/job?"

2024-02-12 10:27 UTC, VallariAg commented
To test this PR, follow instructions in the description of this PR: https://github.com/ceph/teuthology-api/pull/47

https://github.com/ceph/pulpito-ng/assets/50358181/84fe2aac-d224-4dac-a1bc-5f6c1ecfcfec

2024-02-13 21:10 UTC, zmc requested changes
This is looking better than ever!

Something's not working properly if the api returns an error, though; if `/kill/` returns a 500, the UI transitions from "Killing run..." right back to "Are you sure...", without displaying anything related to the failure.

2024-02-13 21:10 UTC, zmc commented on src/components/KillButton/index.tsx
> +  const loggedUser = sessionQuery.data?.session.username;
```suggestion
  const loggedUser = sessionQuery.data?.session?.username;
```

2024-04-09 21:10 UTC, zmc requested changes
Sorry for the delay in retesting this!
I think we need to allow org admins to kill, and I'm getting errors trying to kill runs I own. I can't find details aside from the "Failed!" message that pops up in the UI.
If I dismiss the error dialog and click the button a second time, it skips the confirmation and displays the "Failed!" message again immediately, without making another API request.

2024-04-24 16:39 UTC, VallariAg commented
I have added the logic for letting admins kill all runs on https://github.com/ceph/teuthology-api/pull/55
If the run belongs to the logged-in user, then pulpito-ng will show "Kill" button. If not, then it'll show  "Kill As Admin" button.
For now, pulpito-ng does not verify if user has admin privileges. That check happens on t-api after the request is sent by clicking "Kill As Admin". 

I have improved error handling on t-api so it should not just show "Failed!" now and give more details, please let me know if it still doesn't work!
And the retry on button click problem should also be fixed now.


**To test this PR:**

Setup teuthology-api inside the teuthology container. 
1. Add instructions in teuthology dockerfile to setup t-api inside the teuthology container:
```
SHELL ["/bin/bash", "-c"] 
WORKDIR /
RUN git clone -b admin-kill https://github.com/ceph/teuthology-api && \
    cd /teuthology-api/ && \
    python3 -m venv venv && source ./venv/bin/activate && pip install -e . && \
    export TEUTHOLOGY_API_SERVER_PORT=8083 && \
    exit
WORKDIR /teuthology
....
```
2. In docker-compose file, expose TEUTHOLOGY_API_SERVER_PORT for teuthology service:
```
teuthology:
   ports:
      - 8083:8083
```
3. Start the containers
4. exec into the teuthology container and run these commands:
```
cd /teuthology-api
source ./venv/bin/activate
<add your teuthology-api's .env file> (add `TEUTHOLOGY_PATH=/teuthology` if not present)
uvicorn teuthology_api.main:app --reload --port 8083 --host 0.0.0.0
```

5. Schedule a run on /suite route, using the README payload. 
6. Navigate to the run's page on pulpito-ng and click "Kill run"/"Kill As Admin"

2024-05-29 15:00 UTC, kamoltat submitted a review, later dismissed
Just added some questions regarding exceptions I encountered while testing locally myself.

2024-05-29 15:34 UTC, VallariAg commented
Thank you for reviewing this, I'll take look at both the above problems! Looks like error handling can be improved more too.

2024-06-11 14:51 UTC, VallariAg commented
@kamoltat I have improved error handling so the logs are more readable. 

About the traceback, I think maybe your local teuthology branch might not be up-to-date with remote branch because Zack removed the nuke command from main which I see logged in that traceback. Maybe the latest teuthology commit might not have the problem. 
Also if you see this tracker's traceback (https://tracker.ceph.com/issues/65152) when killing runs, then please ignore because it's a separate problem in tuethology in production which I observed when killing queued runs. 

And for editing ".teuthology.yml" file: there's a note in t-api README that we can use `"--teuthology-branch": "", // necessary for docker setup` in suite request. Ref:
https://github.com/ceph/teuthology-api?tab=readme-ov-file#route-suite

I am also trying to think of ways to improve the setup of running t-api inside the teuthology container so it's not a lot of manual setup.

2024-06-24 18:41 UTC, kamoltat commented
I'm pretty sure this is the issue you were talking about.
I was trying to kill runs with all queued jobs:
<img width="1634" alt="image" src="https://github.com/ceph/pulpito-ng/assets/22287000/3dd36fe8-b2fe-4b25-bc10-0c21eaf88b28">

However, we `running` jobs should be expected to be killed successfully correct?

2024-06-24 18:52 UTC, VallariAg commented
@kamoltat both (running and waiting) seems to have a regression at the moment: https://tracker.ceph.com/issues/66440
I was able to debug the problem, I'll open a PR for a fix tomorrow. 

Though I see in that screenshot that the log trace is not very readable. I have improved that in a recent commit in this PR. Pulling the latest commit of this branch should fix that.

2024-06-24 19:22 UTC, kamoltat commented
> @kamoltat both (running and waiting) seems to have a regression at the moment: https://tracker.ceph.com/issues/66440 I was able to debug the problem, I'll open a PR for a fix tomorrow.
> 
> Though I see in that screenshot that the log trace is not very readable. I have improved that in a recent commit in this PR. Pulling the latest commit of this branch should fix that.

@VallariAg sounds good thanks

2024-06-24 19:23 UTC, kamoltat commented
Putting https://github.com/ceph/teuthology-api/pull/63/files
here so it's easier for me to query when trying to test PR

2024-06-25 07:53 UTC, VallariAg commented
I have updated the docker-compose file to only mount "teuthology_api/src": https://github.com/ceph/teuthology/pull/1957
Now you wouldn't need to manually edit that for the next review, hope that helps!

2024-06-26 15:47 UTC, kamoltat commented
@VallariAg  https://github.com/ceph/teuthology/pull/1959 
this should be resolved right?

2024-06-26 15:59 UTC, VallariAg commented
@kamoltat It'll resolve for running jobs, yes! For waiting there are more regressions (mentioned in the comments of that ticket). 
I haven't gotten around to testing my fix for "waiting" jobs yet, I'll update here soon.

2024-07-17 20:55 UTC, kamoltat commented
Case1: Killing while job is being queued

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/4d78fcb0-b156-4d90-b2f7-cbb3ed7d0458">

2024-08-13 20:38 UTC, zmc commented
The kill button is greyed out for me, on this run: https://pulpito-ng-zmc.ceph.com/runs/zmc-2024-08-13_20:31:57-teuthology:no-ceph-main-distro-default-smithi
I deployed this branch at the URL above. The run is currently queued. Here's the redacted response from t-api's root endpoint:
`{"root":"success","session":{"id": "XXX","username":"zmc","state":"active","role":"admin","access_token":"XXX"}}`

2024-09-18 15:54 UTC, zmc approved these changes

2024-09-18 17:40 UTC, zmc commented
I was able to kill two runs that matched my github username: one with a queued job, and one with a running job. Both behaved properly. A tiny issue is that we don't refresh the job status on the page after killing, but we don't have to block this PR on that.

![Screenshot 2024-09-18 at 11 37 28](https://github.com/user-attachments/assets/4a693bb9-3dc1-4113-a99d-740f0c0f3d94)
![Screenshot 2024-09-18 at 11 30 25](https://github.com/user-attachments/assets/2b2abb41-dd7f-4918-89a7-fb1fa0b16b83)

2024-09-19 20:53 UTC, zmc requested changes
Now that the feature works reliably and we've sorted out the CORS and other issues getting in the way, I'm reminded that we're still showing the button when we know it can't be used either because of permissions, or because the run has completed and there's nothing to kill.

We should hide the button when:
1. The user is logged out
2. The run is finished
3. The user is not an admin, and the run belongs to someone else (90% sure on this one)

I think the above might actually all cases where the button would normally be greyed out.

Sorry to retract an approval @VallariAg, but I bet you'd agree that 1 and 2 are unhelpful, and likely 3 as well. Curious what @kamoltat thinks.

2024-09-20 08:08 UTC, VallariAg commented
@zmc my reasoning for greying out the button is that I wanted to give a message to the user (with tooltip) explaining why they can't kill a run (otherwise they might wonder why they can't see the button). But I 100% agree that not having a button for 1 and 2 would be more intuitive. I can change that!

I think for 3, benefits of having a disabled button is that: 
1. people who don't have admin access (but would want to have it), can know they're missing something. Otherwise, they wouldn't even know that users _can_ have admin access, especially because its a new feature. And it might become a hidden feature. 
2. the disabled button would be a good indicator that they don't own the run and need to use `--owner` while scheduling. If there's no button, it might confuse users why they don't see the button. We can help explain this in the tooltip, and even tell them _who_ is the owner. Example `"Run owned another user <owner name>, you need to be admin user to kill this run"`

2024-09-23 20:17 UTC, zmc commented
Thanks @VallariAg, I think I agree with you about keeping the button in scenario 3 - adding the value to the tooltip is a good idea too.

2024-09-30 23:18 UTC, zmc approved these changes
Thank you so much @Devansh3712 and @VallariAg for making this happen!

2024-09-30 23:19 UTC, merged